### ISSUE TITLE
failed to save D2_all to nifti files using the function dist.plot

### ISSUE THREAD

**Issue by pinghongyeh** [neuralabc/mvcomp#20]
Hello Team, 

Thank you for providing the codes. 
This may not be bugs. 
I was able to calculate all_D22D array feature matrix (size of [145811, 223], ii.e. the same size as of all_mask ), and would save them into nifit files by using disp_plot. 
The mask image has size [192,229,193].   
The IDs is the list of 223 string, e.g. IDs=[ 'NCNC3185', 'NCNC3186', 'NCNC3188', 'NCNC3189', 'NCNC3190', 'NCNC3196', 'NCNC3197', 'NCNC3199', 'NCNC3200', 'NCNC3201', 'NCNC3203', 'NCNC3204', 'NCNC3206', 'NCNC3209',....]

When I used the following command,  

mvc.dist_plot(all_dist = all_D2, all_mask = all_mask, subject_ids = IDs, feat_sub=[],save_results=True,out_dir=feature_results_dir, mask_f=mask_fname, mask_img=None, coordinate=(-10, -50, 10), vmin=None, vmax=5, hist_tr=100, nobin=100)

The error reads, 

number of not NAN voxels:  145811
*** ValueError: NumPy boolean array indexing assignment cannot assign 145811 input values to the 1970710 output values where the mask is true

The error is due to the mismatch of the size of feature mat and the number of voxels in the mask file.  
Do you have any suggestion in fixing this? 

Thank you. 
Ping

**Comment by steelec** [comment]
Thanks Ping, does projecting the data back into the mask and then saving directly through nibabel work as expected?

**Comment by pinghongyeh** [comment]
Hi Christopher,

Thank you for the reply.

In the dist.plot function, it seems to work fine up to the lines (#670 in
the mvcomp.py)
....
...

print("number of non NAN voxels: ", np.count_nonzero(d_out))

d_out = np.mean(all_dist, axis=-1)
m_out[oob_mask] = 0 # just zero the values that are fringe


I have not done saving through nibabel yet (my computer currently has some
issues and it has been frozen up.
Were the indices array needed in order to save it into nifiti file?

Thank you.
Ping
